name: Validation of markdown files

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
  markdown-lint:
    name: Validation files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: DavidAnson/markdownlint-cli2-action@v9

      - name: Lint
        run: markdownlint-cli2 --config=.markdownlint.yml docs/**/*.md
